resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:878f6ce6e065f1c28063ecac0b73eea7f32233e3e09eb57dd098397922481b76
  name: quay.io/siamaksade/spring-petclinic:latest
  newName: quay.io/langley_millard_ibm/spring-petclinic
