resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:f7fc30f5bd6c79c3ad8e8f91c0f979c109f942dcda9864d6bad91bc14290f363
  name: quay.io/siamaksade/spring-petclinic:latest
  newName: quay.io/nickmerrett/spring-petclinic
