resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:fec57c7a77decd66011c20675ba4bc7021de657a94b2fdc7fc355454b5c38ebb
  name: quay.io/siamaksade/spring-petclinic:latest
  newName: quay.io/langley_millard_ibm/spring-petclinic
