resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:8b4938034740232a31f2e5e5037942f160d603c39ea839b3a24b79233c19b2f6
  name: quay.io/siamaksade/spring-petclinic:latest
  newName: quay.io/nickmerrett/spring-petclinic
