resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:4d5b58dd4d0ea50c4b29d3fb4449a392dbb71a39f5ba3eb0eb334571005354b1
  name: quay.io/siamaksade/spring-petclinic:latest
  newName: quay.io/langley_millard_ibm/spring-petclinic
