resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:b2ef5d6ef48b91774286475c3bf92a2bea3d430ab7091d9c8a802c1e8b420166
  name: quay.io/siamaksade/spring-petclinic:latest
  newName: quay.io/nickmerrett/spring-petclinic
