resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: registry-1.docker.io/egrol/spring-boot-log4j-vulnerable:0.1
  newName: quay.io/nickmerrett/spring-boot-log4j-vulnerable
  newTag: 256dd23ed9e25cde3eb892b90ebec1cc487fdd025d3edb58bf90a8c73883878a
